// prisma/customRestaurants.ts
// 40 sample San Diego restaurant entries for seeding

const SAN_DIEGO_IMAGE_URL =
  "https://plus.unsplash.com/premium_vector-1689096693986-e591cd6f2043?q=80&w=2360&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D";

export const customRestaurants = [
  {
    name: "Phil's BBQ",
    userCreated: false,
    description: "Famous for ribs and barbecue in San Diego.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Hodad's",
    userCreated: false,
    description: "Iconic burger joint in Ocean Beach.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "ONE",
    userRating: 4.7,
  },
  {
    name: "The Crack Shack",
    userCreated: false,
    description: "Casual spot for fried chicken and egg sandwiches.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Lucha Libre Taco Shop",
    userCreated: false,
    description: "Creative tacos and wrestling-themed decor.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "ONE",
    userRating: 4.6,
  },
  {
    name: "Point Loma Seafoods",
    userCreated: false,
    description: "Fresh seafood market and eatery by the bay.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Extraordinary Desserts",
    userCreated: false,
    description: "Decadent cakes and desserts in a chic setting.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Juniper & Ivy",
    userCreated: false,
    description: "Trendy New American cuisine in Little Italy.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "THREE",
    userRating: 4.6,
  },
  {
    name: "Born and Raised",
    userCreated: false,
    description: "Upscale steakhouse with rooftop views.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Las Cuatro Milpas",
    userCreated: false,
    description: "Legendary spot for homemade Mexican food.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "ONE",
    userRating: 4.6,
  },
  {
    name: "Cucina Urbana",
    userCreated: false,
    description: "Rustic Italian fare and wine shop.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "The Fish Market",
    userCreated: false,
    description: "Seafood restaurant with harbor views.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Sushi Ota",
    userCreated: false,
    description: "Highly rated sushi in Pacific Beach.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "THREE",
    userRating: 4.7,
  },
  {
    name: "Oscar's Mexican Seafood",
    userCreated: false,
    description: "Casual spot for fish tacos and ceviche.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "The Prado at Balboa Park",
    userCreated: false,
    description: "California cuisine in a historic park setting.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Kettner Exchange",
    userCreated: false,
    description: "Modern American eatery with rooftop lounge.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Puesto",
    userCreated: false,
    description: "Gourmet tacos and craft cocktails.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Ironside Fish & Oyster",
    userCreated: false,
    description: "Trendy seafood spot in Little Italy.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "The Cottage La Jolla",
    userCreated: false,
    description: "Popular for breakfast and brunch in La Jolla.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Hash House A Go Go",
    userCreated: false,
    description: "Farm-fresh comfort food and huge portions.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Blue Water Seafood Market & Grill",
    userCreated: false,
    description: "Fresh fish tacos and sandwiches.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.7,
  },
  {
    name: "The Mission Cafe",
    userCreated: false,
    description: "Healthy breakfast and Latin-inspired dishes.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Cafe 21 Gaslamp",
    userCreated: false,
    description: "Farm-to-table eatery with global flavors.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Tender Greens",
    userCreated: false,
    description: "Fresh salads and plates with local ingredients.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Urban Solace",
    userCreated: false,
    description: "Modern comfort food in North Park.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.4,
  },
  {
    name: "C Level Lounge",
    userCreated: false,
    description: "Waterfront dining with skyline views.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Great Maple",
    userCreated: false,
    description: "Modern American comfort food and brunch.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Snooze, an A.M. Eatery",
    userCreated: false,
    description: "Creative breakfast and brunch chain.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGETARIAN"],
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Truluck's Ocean's Finest Seafood & Crab",
    userCreated: false,
    description: "Upscale seafood and steakhouse.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.6,
  },
  {
    name: "Mister A's",
    userCreated: false,
    description: "Fine dining with panoramic city views.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.7,
  },
  {
    name: "Buona Forchetta",
    userCreated: false,
    description: "Beloved Italian pizzeria and trattoria.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.7,
  },
  {
    name: "Café Gratitudine",
    userCreated: false,
    description: "Vegan restaurant with a positive vibe.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    tags: ["VEGAN"],
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "Harney Sushi",
    userCreated: false,
    description: "Sushi bar with creative rolls and sake.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "The Taco Stand",
    userCreated: false,
    description: "Authentic Tijuana-style tacos.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "ONE",
    userRating: 4.7,
  },
  {
    name: "OB Noodle House",
    userCreated: false,
    description: "Asian fusion and pho in Ocean Beach.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Saffron Thai",
    userCreated: false,
    description: "Longtime Thai eatery with noodles and satay.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
  {
    name: "El Indio Mexican Restaurant",
    userCreated: false,
    description: "Family-run spot for classic Mexican fare.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "ONE",
    userRating: 4.5,
  },
  {
    name: "The Baked Bear",
    userCreated: false,
    description: "Custom ice cream sandwiches.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Pappalecco",
    userCreated: false,
    description: "Italian cafe for gelato and espresso.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.6,
  },
  {
    name: "Donut Bar",
    userCreated: false,
    description: "Gourmet donuts and coffee downtown.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.7,
  },
  {
    name: "Café Coyote",
    userCreated: false,
    description: "Old Town Mexican restaurant with handmade tortillas.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.4,
  },
  {
    name: "Stone Brewing World Bistro & Gardens",
    userCreated: false,
    description: "Craft brewery and restaurant with gardens.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "THREE",
    userRating: 4.5,
  },
  {
    name: "Kono's Cafe",
    userCreated: false,
    description: "Beachside breakfast and brunch in Pacific Beach.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "ONE",
    userRating: 4.6,
  },
  {
    name: "The Red Door",
    userCreated: false,
    description: "Farm-to-table American cuisine in Mission Hills.",
    imageUrl: SAN_DIEGO_IMAGE_URL,
    priceRating: "TWO",
    userRating: 4.5,
  },
];
